services:
  server:
    build: ./server
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    restart: always

  client:
    build:
      context: ./client
      args:
        - VITE_API_URL=http://localhost:5001
    ports:
      - "8080:80"
    depends_on:
      - server
    restart: always
